services:
    auth_service:
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8701}:80'
            - '${APP_DEBUG_PORT:-9001}:9003'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        container_name: auth_service_app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal} client_port=9003'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - '.:/var/www/html'
        networks:
            - sbc
        depends_on:
            - auth_mysql
            - auth_redis

    auth_mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        container_name: auth_db
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sbc-auth-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sbc
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    auth_redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        container_name: auth_redis
        volumes:
            - 'sbc-auth-redis:/data'
        networks:
            - sbc
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mailpit:
        image: axllent/mailpit
        networks:
            - sbc
        ports:
            - "8025:8025"
            - "1025:1025"


    datadog:
        image: gcr.io/datadoghq/agent:7
        environment:
             DD_API_KEY: '${DD_API_KEY}'
             DD_SITE: '${DD_SITE}'
             DD_ENV: local
             DD_SERVICE: your-laravel-app
             DD_LOGS_ENABLED: true
             DD_APM_ENABLED: true
             DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /proc/:/host/proc/:ro
            - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
        ports:
            - "8126:8126"
        networks:
            - sbc

networks:
    sbc:
        driver: bridge
volumes:
    sbc-auth-mysql:
        driver: local
    sbc-auth-redis:
        driver: local
